# Generated by Django 5.0.7 on 2024-08-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='trend',
            field=models.BooleanField(default=False),
        ),
    ]
